### ISSUE TITLE
Gather necessary application assets

### ISSUE THREAD

**Issue by silvanocerza** [evonove/mysthea-app#70]
Missing assets:

- [x] (#74) Latest cards data (codes, descriptions, translations, etc.)
- [x] (#82) Latest cards images
- [x] (#83) Lore text and images and translation
- [x] (#85) Game setup images and text and translation
- [x] (#86) Rulebook download links for every language
- [x] (#87) Newsletter link
